export const defaultBoard: Square[] = [
  { position: 0, isDarkSquare: false },
  { position: 1, isDarkSquare: true, disc: { player: 1, isKing: false } },
  { position: 2, isDarkSquare: false },
  { position: 3, isDarkSquare: true, disc: { player: 1, isKing: false } },
  { position: 4, isDarkSquare: false },
  { position: 5, isDarkSquare: true, disc: { player: 1, isKing: false } },
  { position: 6, isDarkSquare: false },
  { position: 7, isDarkSquare: true, disc: { player: 1, isKing: false } },
  { position: 8, isDarkSquare: true, disc: { player: 1, isKing: false } },
  { position: 9, isDarkSquare: false },
  { position: 10, isDarkSquare: true, disc: { player: 1, isKing: false } },
  { position: 11, isDarkSquare: false },
  { position: 12, isDarkSquare: true, disc: { player: 1, isKing: false } },
  { position: 13, isDarkSquare: false },
  { position: 14, isDarkSquare: true, disc: { player: 1, isKing: false } },
  { position: 15, isDarkSquare: false },
  { position: 16, isDarkSquare: false },
  { position: 17, isDarkSquare: true, disc: { player: 1, isKing: false } },
  { position: 18, isDarkSquare: false },
  { position: 19, isDarkSquare: true, disc: { player: 1, isKing: false } },
  { position: 20, isDarkSquare: false },
  { position: 21, isDarkSquare: true, disc: { player: 1, isKing: false } },
  { position: 22, isDarkSquare: false },
  { position: 23, isDarkSquare: true, disc: { player: 1, isKing: false } },
  { position: 24, isDarkSquare: true },
  { position: 25, isDarkSquare: false },
  { position: 26, isDarkSquare: true },
  { position: 27, isDarkSquare: false },
  { position: 28, isDarkSquare: true },
  { position: 29, isDarkSquare: false },
  { position: 30, isDarkSquare: true },
  { position: 31, isDarkSquare: false },
  { position: 32, isDarkSquare: false },
  { position: 33, isDarkSquare: true },
  { position: 34, isDarkSquare: false },
  { position: 35, isDarkSquare: true },
  { position: 36, isDarkSquare: false },
  { position: 37, isDarkSquare: true },
  { position: 38, isDarkSquare: false },
  { position: 39, isDarkSquare: true },
  { position: 40, isDarkSquare: true, disc: { player: 0, isKing: false } },
  { position: 41, isDarkSquare: false },
  { position: 42, isDarkSquare: true, disc: { player: 0, isKing: false } },
  { position: 43, isDarkSquare: false },
  { position: 44, isDarkSquare: true, disc: { player: 0, isKing: false } },
  { position: 45, isDarkSquare: false },
  { position: 46, isDarkSquare: true, disc: { player: 0, isKing: false } },
  { position: 47, isDarkSquare: false },
  { position: 48, isDarkSquare: false },
  { position: 49, isDarkSquare: true, disc: { player: 0, isKing: false } },
  { position: 50, isDarkSquare: false },
  { position: 51, isDarkSquare: true, disc: { player: 0, isKing: false } },
  { position: 52, isDarkSquare: false },
  { position: 53, isDarkSquare: true, disc: { player: 0, isKing: false } },
  { position: 54, isDarkSquare: false },
  { position: 55, isDarkSquare: true, disc: { player: 0, isKing: false } },
  { position: 56, isDarkSquare: true, disc: { player: 0, isKing: false } },
  { position: 57, isDarkSquare: false },
  { position: 58, isDarkSquare: true, disc: { player: 0, isKing: false } },
  { position: 59, isDarkSquare: false },
  { position: 60, isDarkSquare: true, disc: { player: 0, isKing: false } },
  { position: 61, isDarkSquare: false },
  { position: 62, isDarkSquare: true, disc: { player: 0, isKing: false } },
  { position: 63, isDarkSquare: false }
];
