version: 2.1
orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6

jobs:
  build-test-and-deploy:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn affected:deploy --base=<< pipeline.git.base_revision >> --head=HEAD
      - heroku/deploy-via-git

workflows:
  build-test-and-deploy:
    jobs:
      - build-test-and-deploy
          filters:
            branches:
              only: main

