version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build-test-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: yarn affected:deploy --base=<< pipeline.git.base_revision >> --head=HEAD

workflows:
  build-test-and-deploy:
    jobs:
      - build-test-and-deploy
