name: 'CD'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: "16.15.0"

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build affected
        run: yarn affected:build --base=origin/main~1

      - name: Deploy affected
        run: yarn affected:deploy --base=origin/main~1
        env:
          NETLIFY_TOKEN: ${{secrets.NETLIFY_TOKEN}}

      - name: Check if server was affected
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "dist/apps/server/main.js"

      - name: Deploy
        if: steps.check_files.outputs.files_exists == 'true'
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "react-checkers-game"
          heroku_email: "emanuellarini@hotmail.com"
